"""Shared page builder for the generated guide pages.

Each page module in _build/pages/ supplies metadata and a body template.
Citations are written as [[source_key]] and numbered automatically in order
of first use; the sources list at the foot of the page is generated from
_build/data/sources.json, so a source is defined once for every page.
"""
import html
import json
import os
import re

ROOT = os.path.dirname(os.path.abspath(__file__))
SITE = 'https://commercialevs.co.uk'
CSS_VERSION = 4  # bump when css/site.css changes, here and in hand-written pages

NAV = [('/electric-vans-uk/', 'Vans'), ('/electric-trucks-uk/', 'Trucks'), ('/electric-van-batteries/', 'Batteries'),
       ('/electric-van-fleets-uk/', 'Fleets'), ('/charging-an-electric-van/', 'Charging'),
       ('/diesel-vs-electric-vans/', 'Diesel vs electric'), ('/commercial-electric-vehicles-uk/', 'Grants &amp; rules')]


def load(name):
    with open(os.path.join(ROOT, 'data', name), encoding='utf-8') as f:
        return json.load(f)


SOURCES = load('sources.json')


def nav(current):
    out = []
    for href, label in NAV:
        cur = ' aria-current="page"' if href == current else ''
        out.append(f'      <a href="{href}"{cur}>{label}</a>')
    return '\n'.join(out)


def source_html(key):
    s = SOURCES[key]
    links = []
    for site, url, official in s['links']:
        rel = 'noopener' if official else 'nofollow noopener'
        links.append(f'<a href="{url}" rel="{rel}" target="_blank">{site}</a>')
    return s['label'] + ': ' + '; '.join(links)


def cite(body):
    """Replace [[key]] with numbered links in order of first use; return body and sources list HTML."""
    order = []

    def rep(m):
        k = m.group(1)
        if k not in SOURCES:
            raise KeyError(f'unknown source {k}')
        if k not in order:
            order.append(k)
        n = order.index(k) + 1
        return f'<a href="#s{n}">[{n}]</a>'

    body = re.sub(r'\[\[(\w+)\]\]', rep, body)
    lis = '\n'.join(f'      <li id="s{i + 1}">{source_html(k)}</li>' for i, k in enumerate(order))
    return body, lis


def refs(keys):
    """Citation markers for a list of source keys, e.g. '[[a]] [[b]]'."""
    return ' '.join(f'[[{k}]]' for k in keys)


def page(slug, title, desc, og_desc, crumb, h1, published, modified, body, extra_graph=None):
    url = f'{SITE}/{slug}/'
    body, lis = cite(body)
    jt = title.replace('"', '\\"')
    jd = desc.replace('"', '\\"')
    extra = ''
    if extra_graph:
        extra = ''.join(',\n      ' + json.dumps(g, ensure_ascii=False) for g in extra_graph)
    return f'''<!DOCTYPE html>
<html lang="en-GB">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- Generated by _build/build.py from _build/pages/{slug.replace('-', '_')}.py. Edit the source, not this file. -->
  <title>{html.escape(title, quote=False)}</title>
  <meta name="description" content="{html.escape(desc)}">
  <link rel="canonical" href="{url}">
  <meta name="robots" content="index, follow, max-image-preview:large">
  <meta name="theme-color" content="#0c1512">

  <meta property="og:type" content="article">
  <meta property="og:site_name" content="CommercialEVs.co.uk">
  <meta property="og:title" content="{html.escape(title)}">
  <meta property="og:description" content="{html.escape(og_desc)}">
  <meta property="og:url" content="{url}">
  <meta property="og:image" content="{SITE}/img/og-guides.png">
  <meta property="og:image:width" content="1200">
  <meta property="og:image:height" content="630">
  <meta property="og:image:alt" content="CommercialEVs.co.uk – UK electric van guides">
  <meta property="og:locale" content="en_GB">
  <meta name="twitter:card" content="summary_large_image">

  <link rel="icon" href="/favicon.ico" sizes="48x48">
  <link rel="icon" href="/favicon.svg" type="image/svg+xml">
  <link rel="apple-touch-icon" href="/img/apple-touch-icon.png">

  <script type="application/ld+json">
  {{
    "@context": "https://schema.org",
    "@graph": [
      {{
        "@type": "Article",
        "@id": "{url}#article",
        "headline": "{jt}",
        "description": "{jd}",
        "datePublished": "{published}",
        "dateModified": "{modified}",
        "inLanguage": "en-GB",
        "image": "{SITE}/img/og-guides.png",
        "mainEntityOfPage": "{url}",
        "author": {{ "@type": "Organization", "@id": "{SITE}/#organization", "name": "CommercialEVs.co.uk", "url": "{SITE}/", "logo": "{SITE}/img/logo.png" }},
        "publisher": {{ "@type": "Organization", "@id": "{SITE}/#organization", "name": "CommercialEVs.co.uk", "url": "{SITE}/", "logo": "{SITE}/img/logo.png" }},
        "isPartOf": {{ "@type": "WebSite", "name": "CommercialEVs.co.uk", "url": "{SITE}/" }}
      }},
      {{
        "@type": "BreadcrumbList",
        "itemListElement": [
          {{ "@type": "ListItem", "position": 1, "name": "CommercialEVs.co.uk", "item": "{SITE}/" }},
          {{ "@type": "ListItem", "position": 2, "name": "{crumb}", "item": "{url}" }}
        ]
      }}{extra}
    ]
  }}
  </script>

  <!-- Google Analytics 4 -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=G-9Y22D7RMQH"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){{dataLayer.push(arguments);}}
    gtag('js', new Date());
    gtag('config', 'G-9Y22D7RMQH');
  </script>

  <!-- Google Tag Manager -->
  <script>(function(w,d,s,l,i){{w[l]=w[l]||[];w[l].push({{'gtm.start':
    new Date().getTime(),event:'gtm.js'}});var f=d.getElementsByTagName(s)[0],
    j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
    'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
    }})(window,document,'script','dataLayer','GTM-M4XK23H');</script>

  <link href="/css/site.css?v={CSS_VERSION}" rel="stylesheet">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600;800&display=swap" rel="stylesheet" media="print" onload="this.media='all'">
</head>
<body>
  <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-M4XK23H" height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>

  <header class="topbar">
    <a class="brandlink" href="/">CommercialEVs<span class="tld">.co.uk</span></a>
    <nav class="topnav" aria-label="Guides">
{nav('/' + slug + '/')}
    </nav>
  </header>

  <main class="doc">
    <nav class="crumbs" aria-label="Breadcrumb"><a href="/">Home</a> / {crumb}</nav>

    <h1>{h1}</h1>
{body.rstrip()}

    <h2 id="sources">Sources</h2>
    <ol class="sources">
{lis}
    </ol>
  </main>

  <footer class="footer">
    <p><a href="/">CommercialEVs.co.uk</a> &middot; <a href="/about/">About</a> &middot; <a href="/privacy/">Privacy</a> &middot; <a href="/domain-for-sale/">Domain for sale</a></p>
  </footer>
</body>
</html>
'''
